<?php

namespace Database\Seeders;

use App\Models\CoreTransactionCode;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CoreTransactionCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $transactionCodes = [
            [
                'transaction_name' => 'FRMS-Transtype',
                'transaction_key' => 'TYPE',
                'identitycode' => 'LIQUIDATION',
                'description' => 'Liquidation',
                'trans_value' => 0,
                'sortorder' => 1,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Transtype',
                'transaction_key' => 'TYPE',
                'identitycode' => 'REIMBURSEMENT',
                'description' => 'Reimbursement',
                'trans_value' => 0,
                'sortorder' => 2,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Transtype',
                'transaction_key' => 'TYPE',
                'identitycode' => 'REPLENISHMENT',
                'description' => 'Replenishment',
                'trans_value' => 0,
                'sortorder' => 3,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Frequency',
                'transaction_key' => 'TYPE',
                'identitycode' => 'ANNUALLY',
                'description' => 'Annually',
                'trans_value' => 0,
                'sortorder' => 1,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Frequency',
                'transaction_key' => 'TYPE',
                'identitycode' => 'DAILY',
                'description' => 'Daily',
                'trans_value' => 0,
                'sortorder' => 2,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Frequency',
                'transaction_key' => 'TYPE',
                'identitycode' => 'WEEKLY',
                'description' => 'Weekly',
                'trans_value' => 0,
                'sortorder' => 3,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Frequency',
                'transaction_key' => 'TYPE',
                'identitycode' => 'MONTHLY',
                'description' => 'Monthly',
                'trans_value' => 0,
                'sortorder' => 4,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Frequency',
                'transaction_key' => 'TYPE',
                'identitycode' => 'INCIDENTAL',
                'description' => 'Incidental',
                'trans_value' => 0,
                'sortorder' => 5,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Frequency',
                'transaction_key' => 'TYPE',
                'identitycode' => 'MONTHLY/INCIDENTAL',
                'description' => 'Monthly/Incidental',
                'trans_value' => 0,
                'sortorder' => 6,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Frequency',
                'transaction_key' => 'TYPE',
                'identitycode' => 'SEMI-ANNUALLY',
                'description' => 'Semi-Annually',
                'trans_value' => 0,
                'sortorder' => 7,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Vat',
                'transaction_key' => 'TYPE',
                'identitycode' => 'VAT REGISTER',
                'description' => 'VAT Register',
                'trans_value' => 1.12,
                'sortorder' => 7,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
             [
                'transaction_name' => 'FRMS-Vat',
                'transaction_key' => 'TYPE',
                'identitycode' => 'NON-VAT',
                'description' => 'Non-VAT',
                'trans_value' => 0,
                'sortorder' => 8,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            // FRMS Account Codes
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '310',
                'description' => 'Payable to Employee',
                'trans_value' => 0,
                'sortorder' => 1,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '502',
                'description' => 'Manpower: Allowances',
                'trans_value' => 0,
                'sortorder' => 2,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '506',
                'description' => 'Manpower: Salaries and Wages',
                'trans_value' => 0,
                'sortorder' => 3,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '511',
                'description' => 'Manpower: Stripper Labor Cost',
                'trans_value' => 0,
                'sortorder' => 4,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '513',
                'description' => 'Manpower: Uniform/PPE',
                'trans_value' => 0,
                'sortorder' => 5,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '530',
                'description' => 'Investment: Office - Materials/St',
                'trans_value' => 0,
                'sortorder' => 6,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '532',
                'description' => 'Investment: Warehouse - Repair',
                'trans_value' => 0,
                'sortorder' => 7,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '533',
                'description' => 'Investment: Warehouse- Materia',
                'trans_value' => 0,
                'sortorder' => 8,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '535',
                'description' => 'Investment: Trucks - Repairs and Maintenance',
                'trans_value' => 0,
                'sortorder' => 9,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '605',
                'description' => 'Other Expenses: Taxes/Permits/L',
                'trans_value' => 0,
                'sortorder' => 10,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '608',
                'description' => 'Other Expenses: Delivery Expense',
                'trans_value' => 0,
                'sortorder' => 11,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '609',
                'description' => 'Other Expenses: Gas - Trucks',
                'trans_value' => 0,
                'sortorder' => 12,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '612',
                'description' => 'Other Expenses: Meals/Drinks',
                'trans_value' => 0,
                'sortorder' => 13,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '613',
                'description' => 'Other Expenses: Miscellaneous E',
                'trans_value' => 0,
                'sortorder' => 14,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '614',
                'description' => 'Other Expenses: Parking Fee',
                'trans_value' => 0,
                'sortorder' => 15,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '617',
                'description' => 'Other Expenses: Transportation and Travel',
                'trans_value' => 0,
                'sortorder' => 16,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ],
            [
                'transaction_name' => 'FRMS-Account-Code',
                'transaction_key' => 'TYPE',
                'identitycode' => '620',
                'description' => 'Financing: Bank Service Charge',
                'trans_value' => 0,
                'sortorder' => 17,
                'isactive' => 1,
                'createdby' => 'system',
                'updatedby' => null,
            ]

        ];

        foreach ($transactionCodes as $code) {
            CoreTransactionCode::updateOrCreate(
                [
                    'transaction_name' => $code['transaction_name'],
                    'transaction_key' => $code['transaction_key'],
                    'identitycode' => $code['identitycode']
                ],
                $code
            );
        }
    }
}
